set_davis_time:
  name: Set Davis Time
  description: Set the time of the Davis weather station
get_davis_time:
  name: Get Davis Time
  description: Get the time of the Davis weather station
get_raw_data:
  name: Get Raw Data
  description: Get the raw, unprocessed data from the last fetch
get_info:
  name: Get Information
  description: Get information about firmware and diagnostics
set_yearly_rain:
  name: Set Yearly Rain
  description: Set yearly rain in clicks
  fields:
    rain_clicks:
      name: "Rain Clicks"
      description: Rain in clicks (depending on setup one click = 0.01" or 0.2mm)
      required: true
      example: 500
      selector:
        number:
set_archive_period:
  name: Set Archive Period
  description: "Set the archive period in minutes. WARNING: All stored archive data will be erased!!!"
  fields:
    archive_period:
      name: "Archive Period"
      description: "Archive Period in minutes"
      required: true
      example: 10
      selector:
        select:
          options:
            - "1"
            - "5"
            - "10"
            - "15"
            - "30"
            - "60"
            - "120"

