set_davis_time:
get_davis_time:
get_raw_data:
get_info:
set_yearly_rain:
  fields:
    rain_clicks:
      required: true
      example: 500
      selector:
        number:
set_archive_period:
  fields:
    archive_period:
      required: true
      example: 10
      selector:
        select:
          options:
            - "1"
            - "5"
            - "10"
            - "15"
            - "30"
            - "60"
            - "120"

